name: Build Pages
on:
    push:
        branches:
            - main
            - docs-setup
    workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup
        run: |
            sudo apt update -q
            sudo apt install -yy python python3-pip
            pip install -r tools/requirements.txt
      -
        name: Docs
        run: |
            ./tools/schema-merge.py
            ./tools/mkdocs build -d site
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

