name: Build Pages
on:
    push:
        branches:
            - main
            - docs-setup
    workflow_dispatch:
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup
        run: |
            sudo apt update -q
            sudo apt install -yy python python3-pip
            pip install -r tools/requirements.txt
      -
        name: Docs
        run: |
            ./tools/schema-merge.py
            ./tools/mkdocs build -d site
      -
        name: Setup Pages
        uses: actions/configure-pages@v4
      -
        name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
            path: 'site'
      -
        name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

